// <auto-generated />
using System;
using ArrowThing.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArrowThing.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427052535_AddEndlessScores")]
    partial class AddEndlessScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArrowThing.Server.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Event");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.EndlessScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("integer");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Clears")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("LongestCombo")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ReplayJsonGz")
                        .HasColumnType("bytea");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("TuningsVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BoardWidth", "BoardHeight")
                        .IsUnique();

                    b.HasIndex("BoardWidth", "BoardHeight", "Clears", "DurationSeconds");

                    b.ToTable("EndlessScores");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxArrowLength")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SnapshotStrippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.LobbyEvent", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<int?>("ArrowIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("TapX")
                        .HasColumnType("real");

                    b.Property<float?>("TapY")
                        .HasColumnType("real");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LobbyId", "Seq");

                    b.ToTable("LobbyEvents");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.LobbyRegistration", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("AccumulatedMillis")
                        .HasColumnType("bigint");

                    b.Property<int>("ClearCount")
                        .HasColumnType("integer");

                    b.Property<string>("ColorAtJoin")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("DisplayNameAtJoin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstClearAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LobbyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyRegistrations");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.LobbySnapshot", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("Format")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LobbyId");

                    b.ToTable("LobbySnapshots");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("integer");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxArrowLength")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ReplayJsonGz")
                        .HasColumnType("bytea");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoardWidth", "BoardHeight", "Time");

                    b.HasIndex("UserId", "BoardWidth", "BoardHeight")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoopColor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceOtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeviceOtpCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceOtpPendingDeviceIdHash")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text");

                    b.Property<int?>("FlagTriggerBoardHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("FlagTriggerBoardWidth")
                        .HasColumnType("integer");

                    b.Property<string>("FlagTriggerGameId")
                        .HasColumnType("text");

                    b.Property<int?>("FlagTriggerSeed")
                        .HasColumnType("integer");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastDeviceOtpEmailAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPasswordResetEmailAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastVerificationEmailAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("text");

                    b.Property<string>("PendingEmailCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PendingEmailCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.EndlessScore", b =>
                {
                    b.HasOne("ArrowThing.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("ArrowThing.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.Score", b =>
                {
                    b.HasOne("ArrowThing.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrowThing.Server.Models.UserDevice", b =>
                {
                    b.HasOne("ArrowThing.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
